import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "ceify";
    width: 800px;
    height: 300px;

    in-out property <string> selected_file;
    in-out property <string> saved_to;
    in-out property <string> status_text;

    callback select_file();

    VerticalLayout {
        spacing: 16px;
        padding: 24px;

        Text {
            text: "ceify";
            font-size: 28px;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            spacing: 12px;
            
            Text {
                text: "Input:";
                width: 80px;
                vertical-alignment: center;
            }

            Rectangle {
                border-width: 1px;
                border-color: #808080;
                height: 32px;

                Text {
                    text: selected_file;
                    vertical-alignment: center;
                }
            }
        }

        HorizontalLayout {
            spacing: 12px;

            Text {
                text: "Output:";
                width: 80px;
                vertical-alignment: center;
            }

            Rectangle {
                border-width: 1px;
                border-color: #808080;
                height: 32px;

                Text {
                    text: saved_to;
                    wrap: word-wrap;
                    vertical-alignment: center;
                }
            }
        }

        HorizontalLayout {
            alignment: center;

            Button {
                text: "Select file and convert";

                clicked => {
                    root.select_file();
                }
            }
        }

        Text {
            text: status_text;
            color: #404040;
            horizontal-alignment: center;
        }

         Text {
            text: "Version: 1.0.0 (c) 2026 Pavel Pleskunov";
            color: #404040;
            horizontal-alignment: center;
        }
    }
}